on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

name: Build Component Container Images And Submit Metadata To Reliza Hub

jobs:
  build-docs:
    permissions:
      id-token: write
    name: Build And Push Documentation Site
    runs-on: ubuntu-latest
    steps:
      - name: ReARM Build And Submit Documentation Release
        uses: relizaio/rearm-docker-action@48eec1fefda3a07134766f31ba22b76834ab647b # v.1.10.2
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rearm-documentation
          rearm_api_id: ${{ secrets.RELIZA_REARM_DOCS_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REARM_DOCS_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: documentation_site
          enable_sbom: true
          source_code_sbom_type: 'npm'
          enable_public_cosign_sigstore: 'true'
  build-docs-helm:
    permissions:
      contents: write
      id-token: write
    name: Build And Push Documentation Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: RelizaHub Build And Submit Documentation Helm metadata action
        uses: relizaio/rearm-helm-action@9a651183239708b2ef7a01f55039d264e9f54dfc # v1.7.3
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com/library
          helm_chart_name: rearm-documentation-helm
          rearm_api_id: ${{ secrets.RELIZA_REARM_DOCS_HELM_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REARM_DOCS_HELM_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: deploy/helm/rearm-documentation-helm
          enable_sbom: true
          enable_public_cosign_sigstore: true
          limit_to_branches: main
  build-landing-helm:
    permissions:
      contents: write
      id-token: write
    name: Build And Push ReARM Landing Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: RelizaHub Build And Submit ReARM Landing Helm metadata action
        uses: relizaio/rearm-helm-action@9a651183239708b2ef7a01f55039d264e9f54dfc # v1.7.3
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com/library
          helm_chart_name: rearm-landing-helm
          rearm_api_id: ${{ secrets.RELIZA_REARM_LANDING_HELM_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REARM_LANDING_HELM_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: deploy/helm/rearm-landing-helm
          enable_sbom: true
          enable_public_cosign_sigstore: true
          limit_to_branches: main
  build-rearm-helm:
    permissions:
      contents: write
      id-token: write
    name: Build And Push ReARM Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Build And Submit ReARM Helm to ReARM
        uses: relizaio/rearm-helm-action@9a651183239708b2ef7a01f55039d264e9f54dfc # v1.7.3
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com/library
          helm_chart_name: rearm
          rearm_api_id: ${{ secrets.RELIZA_REARM_HELM_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REARM_HELM_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: deploy/helm/rearm-helm
          enable_sbom: true
          enable_public_cosign_sigstore: true
          push_to_rearm_mirror: 'true'
          rearm_mirror_api_id: ${{ secrets.REARM_REARM_HELM_API_ID }}
          rearm_mirror_api_key: ${{ secrets.REARM_REARM_HELM_API_KEY }}
          rearm_mirror_api_url: https://demo.rearmhq.com
          limit_to_branches: main
  build-ui:
    permissions:
      id-token: write
    name: Build And Push ReARM UI
    runs-on: ubuntu-latest
    steps:
      - name: ReARM Build And Submit UI Release
        uses: relizaio/rearm-docker-action@48eec1fefda3a07134766f31ba22b76834ab647b # v.1.10.2
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rearm-ui
          rearm_api_id: ${{ secrets.RELIZA_REARM_UI_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REARM_UI_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: ui
          enable_sbom: true
          source_code_sbom_type: 'npm'
          enable_public_cosign_sigstore: 'true'
          enable_codeql: 'true'
          codeql_language: 'javascript'
          push_to_rearm_mirror: 'true'
          rearm_mirror_api_id: ${{ secrets.REARM_REARM_UI_API_ID }}
          rearm_mirror_api_key: ${{ secrets.REARM_REARM_UI_API_KEY }}
          rearm_mirror_api_url: https://demo.rearmhq.com
  build-backend:
    permissions:
      id-token: write
    name: Build And Push ReARM Backend
    runs-on: ubuntu-latest
    steps:
      - name: Build And Submit Backend Release to ReARM
        uses: relizaio/rearm-docker-action@48eec1fefda3a07134766f31ba22b76834ab647b # v.1.10.2
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rearm-backend
          rearm_api_id: ${{ secrets.RELIZA_REARM_BACKEND_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REARM_BACKEND_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: backend
          enable_sbom: true
          source_code_sbom_type: 'custom'
          enable_public_cosign_sigstore: 'true'
          enable_codeql: 'true'
          codeql_language: 'custom'
          push_to_rearm_mirror: 'true'
          rearm_mirror_api_id: ${{ secrets.REARM_REARM_BACKEND_API_ID }}
          rearm_mirror_api_key: ${{ secrets.REARM_REARM_BACKEND_API_KEY }}
          rearm_mirror_api_url: https://demo.rearmhq.com
  build-oci-service:
    permissions:
      id-token: write
    name: Build And Push ReARM OCI Service
    runs-on: ubuntu-latest
    steps:
      - name: ReARM Build And Submit ReARM OCI Service Release
        uses: relizaio/rearm-docker-action@48eec1fefda3a07134766f31ba22b76834ab647b # v.1.10.2
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rearm-oci-artifact-service
          rearm_api_id: ${{ secrets.RELIZA_REARM_OCI_ARTIFACT_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REARM_OCI_ARTIFACT_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: oci-artifact-service
          enable_sbom: true
          source_code_sbom_type: 'custom'
          enable_public_cosign_sigstore: 'true'
          enable_codeql: 'true'
          codeql_language: 'custom'
          push_to_rearm_mirror: 'true'
          rearm_mirror_api_id: ${{ secrets.REARM_REARM_OCI_ARTIFACT_API_ID }}
          rearm_mirror_api_key: ${{ secrets.REARM_REARM_OCI_ARTIFACT_API_KEY }}
          rearm_mirror_api_url: https://demo.rearmhq.com
  build-keycloak:
    permissions:
      id-token: write
    name: Build And Push ReARM Keycloak
    runs-on: ubuntu-latest
    steps:
      - name: Build And Submit ReARM Keycloak Release to ReARM
        uses: relizaio/rearm-docker-action@48eec1fefda3a07134766f31ba22b76834ab647b # v.1.10.2
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rearm-keycloak
          rearm_api_id: ${{ secrets.RELIZA_REARM_KEYCLOAK_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REARM_KEYCLOAK_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: keycloak
          enable_sbom: true
          source_code_sbom_type: 'none'
          enable_public_cosign_sigstore: 'true'
          push_to_rearm_mirror: 'true'
          rearm_mirror_api_id: ${{ secrets.REARM_REARM_KEYCLOAK_API_ID }}
          rearm_mirror_api_key: ${{ secrets.REARM_REARM_KEYCLOAK_API_KEY }}
          rearm_mirror_api_url: https://demo.rearmhq.com
  build-rearm-landing:
    permissions:
      id-token: write
    name: Build And Push ReARM Landing Website rearmhq.com
    runs-on: ubuntu-latest
    steps:
      - name: ReARM Build And Submit ReARM Landing Release
        uses: relizaio/rearm-docker-action@48eec1fefda3a07134766f31ba22b76834ab647b # v.1.10.2
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rearm-landing
          rearm_api_id: ${{ secrets.RELIZA_REARM_LANDING_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REARM_LANDING_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: landing_site
          enable_sbom: true
          source_code_sbom_type: 'npm'
          enable_public_cosign_sigstore: 'true'
          enable_codeql: 'true'
          codeql_language: 'javascript'
  build-rebom-backend:
    permissions:
      id-token: write
    name: Build And Push Rebom Backend
    runs-on: ubuntu-latest
    steps:
      - name: ReARM Build And Submit Rebom Backend Release
        uses: relizaio/rearm-docker-action@48eec1fefda3a07134766f31ba22b76834ab647b # v.1.10.2
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rebom-backend
          rearm_api_id: ${{ secrets.RELIZA_REBOM_BACKEND_API_ID }}
          rearm_api_key: ${{ secrets.RELIZA_REBOM_BACKEND_API_KEY }}
          rearm_api_url: https://reliza.rearmhq.com
          path: rebom-backend
          enable_sbom: true
          source_code_sbom_type: 'npm'
          enable_public_cosign_sigstore: 'true'
          enable_codeql: 'true'
          codeql_language: 'javascript'
          push_to_rearm_mirror: 'true'
          rearm_mirror_api_id: ${{ secrets.REARM_REBOM_BACKEND_API_ID }}
          rearm_mirror_api_key: ${{ secrets.REARM_REBOM_BACKEND_API_KEY }}
          rearm_mirror_api_url: https://demo.rearmhq.com
          
